### Moayyed Mesleh

# PyTorch

Fundamental of pytorch basics

## Create a (scaler, vector, matrix, tensor)

In [1]:
import torch
# Check the version of PyTorch
print(torch.__version__)

2.1.0+cu121


In [2]:
# Create a tensor of a scalar value, where the scalar refers to a single number
scalar = torch.tensor(5)
scalar

tensor(5)

In [3]:
# Find the dimension of the tensor, scalar alwayes have zero dimension
scalar.ndim

0

In [4]:
# The data type of the tensor
scalar.dtype

torch.int64

In [5]:
# Get tensor back as python int
scalar_py = scalar.item()
print(f"The tensor after convert it bak to python intger: {scalar_py}")
print(f"The data type of it: {type(scalar_py)}")

The tensor after convert it bak to python intger: 5
The data type of it: <class 'int'>


In [6]:
# Vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [7]:
# The number of dimensions for a vector
vector.ndim

1

In [8]:
# Matrix
matrix = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8]])
matrix

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [9]:
# The number of dimensions
matrix.ndim

2

In [10]:
# Create tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

torch.Size([2, 4, 3])

To clarify, the tensor has multiple dimensions as follows:

* A tensor with zero dimensions is a scalar.
* A tensor with one dimension is called a vector.
* A tensor with two dimensions is called a matrix.
* It is common to refer to a tensor with more than three dimensions simply as a tensor.

## Create a random tensor

In [13]:
# Create a random tensor given the size
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0338, 0.7396, 0.7660, 0.5851],
        [0.9443, 0.7977, 0.3541, 0.9636],
        [0.9698, 0.7879, 0.5866, 0.2403]])

In [14]:
# Create a random tensor of image size
image_size_random_tensor = torch.rand(size=(256, 256, 3))
image_size_random_tensor.shape, image_size_random_tensor.ndim

(torch.Size([256, 256, 3]), 3)

In [15]:
image_size_random_tensor

tensor([[[0.7581, 0.0678, 0.1422],
         [0.2171, 0.3682, 0.2415],
         [0.5009, 0.6302, 0.6224],
         ...,
         [0.3267, 0.2310, 0.1014],
         [0.6395, 0.7436, 0.3482],
         [0.0645, 0.4099, 0.2467]],

        [[0.6081, 0.8017, 0.2876],
         [0.3115, 0.3083, 0.2703],
         [0.0761, 0.2974, 0.0776],
         ...,
         [0.5894, 0.2711, 0.6351],
         [0.1976, 0.0985, 0.5893],
         [0.6710, 0.2026, 0.6776]],

        [[0.5403, 0.1048, 0.3222],
         [0.8374, 0.7098, 0.0347],
         [0.7007, 0.5307, 0.8156],
         ...,
         [0.9992, 0.2465, 0.8691],
         [0.7393, 0.4843, 0.3928],
         [0.3787, 0.2775, 0.1521]],

        ...,

        [[0.1377, 0.9438, 0.0467],
         [0.1805, 0.5655, 0.0663],
         [0.7816, 0.9001, 0.7567],
         ...,
         [0.1470, 0.9397, 0.4189],
         [0.1064, 0.5543, 0.8518],
         [0.5971, 0.1358, 0.8008]],

        [[0.1900, 0.5128, 0.8735],
         [0.6931, 0.4483, 0.7889],
         [0.

## Zeros and Ones

In [16]:
# Create a tensor of zero values
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
zeros.dtype

torch.float32

In [18]:
# Of ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

## The arange and tensors-like

In [20]:
# Use arange function to create a tensor of values between to numbers
one_to_ten = torch.arange(1, 10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
zeros_2 = torch.zeros_like(random_tensor) ## Converting an existing  tensor to zeros of the same shape (size)
zeros_2

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Tensor Datatype

In [22]:
tensor_32 = torch.tensor([2., 4., 5.],
                         dtype=None,## The default data type of the integers is int64 and for floats is float32
                         device=None,## cpu, cuda
                         requires_grad=False)
tensor_32

tensor([2., 4., 5.])

In [23]:
tensor_32.dtype

torch.float32

In [24]:
# Convert the datatype of the tensor
tensor_16 = tensor_32.type(torch.float16)
tensor_16

tensor([2., 4., 5.], dtype=torch.float16)

## Getting Tensor Attributes

In [25]:
a_tensor = torch.rand((3, 4), dtype=torch.float64)
a_tensor

tensor([[0.4412, 0.0404, 0.4903, 0.6450],
        [0.6796, 0.0505, 0.7742, 0.9611],
        [0.4933, 0.0385, 0.3210, 0.4360]], dtype=torch.float64)

In [26]:
print(f"A random tensor:\n {a_tensor}\n")
print(f"The shape of the `a_tensor`: {a_tensor.shape}")
print(f"The device: {a_tensor.device}")

A random tensor:
 tensor([[0.4412, 0.0404, 0.4903, 0.6450],
        [0.6796, 0.0505, 0.7742, 0.9611],
        [0.4933, 0.0385, 0.3210, 0.4360]], dtype=torch.float64)

The shape of the `a_tensor`: torch.Size([3, 4])
The device: cpu


## Manipulating Tensors

In [27]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [28]:
tensor.shape

torch.Size([3])

In [29]:
# Elementwise multiplication
tensor * tensor

tensor([1, 4, 9])

In [30]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
# We want to calculate the time taken by for loop vs the PyTorch `matmul` function
# For loob of matrix multiplication
%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.15 µs
tensor(14)


In [32]:
%time
torch.matmul(tensor, tensor)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.44 µs


tensor(14)

* Pytorch use someting called vectorization to crush the numbers, and it's faster than the for loob. The difference of time going to be obvious with larg tensors

## Tensor aggregation

In [33]:
tensor = torch.arange(start=1, end=100, step=10)
tensor

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
tensor.min()

tensor(1)

In [35]:
tensor.max()

tensor(91)

In [36]:
tensor.sum()

tensor(460)

In [37]:
tensor.type(torch.float32).mean()   # For the mean, the tensor should be of a floating-point data type

tensor(46.)

In [38]:
print(f"The min value in the tensor is: {torch.min(tensor)} ")
print(f"The max value in the tensor is: {torch.max(tensor)} ")
print(f"The sum of tensor elements is: {torch.sum(tensor)}" )
print(f"The mean of the elements in the tensor is: {torch.mean(tensor, dtype=torch.float32)}")

The min value in the tensor is: 1 
The max value in the tensor is: 91 
The sum of tensor elements is: 460
The mean of the elements in the tensor is: 46.0


In [39]:
# The argmax function returns the index (position) of the maximum value.
tensor.argmax()

tensor(9)

In [40]:
# # The argmax function returns the index (position) of the minimum value.
tensor.argmin()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing

### Reshaping

In [41]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
r = x.reshape(9, 1) # 9 rows with 1 column
r

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [43]:
x    # We notice that the original value didn't change because we declared a new variable `r`

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

### View

In [44]:
z = x.view(9, 1)
z

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [45]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
# When we change the value of one of the elements in `z` it's going to be change on `x`, because thay share the same memory
z[0, 0] = 4
z, x

(tensor([[4.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stacking

In [47]:
# Concatenate many tensors in one
x_stacked = torch.stack([x,x,x,x], dim=0) # dim zero indicates the rows, and dim one refers to the columns
x_stacked

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [48]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[4., 4., 4., 4.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

### Permute
Permuting to transform the order of tensor data dimensions

In [49]:
x_image = torch.rand((224,224,3))  # Creating random tensor of image
x_image.shape

torch.Size([224, 224, 3])

In [50]:
x_premute = x_image.permute(2, 0, 1)
x_premute.shape

torch.Size([3, 224, 224])

In [51]:
x_image[0, 0, 0] = 3.43  # Changing the first element value, will change it in `x_premute` because thay stord in the same location
x_image

tensor([[[3.4300, 0.0882, 0.2255],
         [0.3255, 0.8107, 0.2344],
         [0.7723, 0.9704, 0.1113],
         ...,
         [0.8257, 0.7763, 0.6141],
         [0.1912, 0.9139, 0.3739],
         [0.5168, 0.8309, 0.6403]],

        [[0.6494, 0.5264, 0.6334],
         [0.3606, 0.8300, 0.8053],
         [0.5384, 0.1552, 0.3880],
         ...,
         [0.8043, 0.5301, 0.1902],
         [0.8206, 0.0220, 0.7343],
         [0.0128, 0.1348, 0.3173]],

        [[0.4708, 0.4101, 0.0308],
         [0.6819, 0.2751, 0.6277],
         [0.0536, 0.3265, 0.9830],
         ...,
         [0.6527, 0.6294, 0.2589],
         [0.6363, 0.6140, 0.3917],
         [0.3589, 0.8878, 0.8392]],

        ...,

        [[0.7437, 0.4891, 0.1765],
         [0.1791, 0.6476, 0.0858],
         [0.0704, 0.5483, 0.9536],
         ...,
         [0.1935, 0.7502, 0.3252],
         [0.4331, 0.4798, 0.1094],
         [0.9134, 0.1990, 0.9832]],

        [[0.6552, 0.4452, 0.9343],
         [0.2703, 0.8055, 0.9579],
         [0.

In [52]:
x_premute[0, 0, 0]

tensor(3.4300)

### Indexing

In [53]:
x = torch.arange(1, 13).reshape(1, 4, 3)
x.shape, x

(torch.Size([1, 4, 3]),
 tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]))

In [54]:
x[:, 0]

tensor([[1, 2, 3]])

In [55]:
x[:, :, 2]

tensor([[ 3,  6,  9, 12]])

## PyTorch and Numpy

In [56]:
import numpy as np
import torch

# Numpy to tensor
array = np.arange(1.0, 10.0).astype(np.float32)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [57]:
tensor.dtype

torch.float32

In [58]:
# The new tensor dosen't change if we changed the array
array = array + 10
array, tensor

(array([11., 12., 13., 14., 15., 16., 17., 18., 19.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [59]:
# Tensor to Numpy
tesnor = torch.ones(7,)
array = tensor.numpy()
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

## Reproducability (take random out of random)

**random seed**

In [60]:
torch.manual_seed(42)
torch.rand(3, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

## GPU

In [61]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-619c0fd6-d9f4-6362-4d67-37d6c1941e7a)


In [62]:
# Check the GPU access with pytorch
import torch
torch.cuda.is_available()   #cuda is nvidia programming interface thats allow us to use GPUs for numircal computing

True

In [63]:
# Setup the device we will work on in PyTorch (device agnostice code)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [64]:
# Number of GPUs
torch.cuda.device_count()

1

## Device

In [65]:
tensor1 = torch.tensor([1, 2, 3])  #the device in defulte is a cpu
tensor1, tensor1.device

(tensor([1, 2, 3]), device(type='cpu'))

In [66]:
# copy it to gpu
tensor2 = tensor1.to(device)
tensor2, tensor2.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [67]:
# copy it back to cpu
tensor3 = tensor2.cpu()
tensor3, tensor3.device

(tensor([1, 2, 3]), device(type='cpu'))